
###################################################################################################
#### MOVE BASE ####################################################################################

# http://wiki.ros.org/move_base#Parameters

base_global_planner:        global_planner/GlobalPlanner
#base_local_planner:         dwa_local_planner/DWAPlannerROS
base_local_planner:         eband_local_planner/EBandPlannerROS
controller_frequency:       15.0
planner_patience:           5.0
controller_patience:        15.0
conservative_reset_dist:    3.0
recovery_behavior_enabled:  true
clearing_rotation_allowed:  true
shutdown_costmaps:          false
oscillation_timeout:        0.0
oscillation_distance:       0.5
planner_frequency:          0.0
max_planning_retries:       -1



###################################################################################################
#### GLOBAL PLANNER ###############################################################################

# http://wiki.ros.org/global_planner#Parameters

#GlobalPlanner:
#    allow_unknown:        false
#    default_tolerance:    0.0
#    visualize_potential:  false
#    use_dijkstra:         true
#    use_quadratic:        true
#    use_grid_path:        false
#    old_navfn_behavior:   false



###################################################################################################
#### GLOBAL COSTMAP ###############################################################################

# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
# http://wiki.ros.org/costmap_2d/hydro/staticmap
# http://wiki.ros.org/costmap_2d/hydro/obstacles
# http://wiki.ros.org/costmap_2d/hydro/inflation

global_costmap:
    global_frame:              "/map"
    robot_base_frame:          "/base_link"
    transform_tolerance:       1.5
    update_frequency:          0.5
    static_map:                true
    publish_frequency:         2.0
    rolling_window:            false
    always_send_full_costmap:  true
    footprint_padding:         0.03
    plugins:
     - name: static_layer
       type: "costmap_2d::StaticLayer"
     - name: obstacle_layer
       type: "costmap_2d::ObstacleLayer"
     - name: inflation_layer
       type: "costmap_2d::InflationLayer"

    #footprint: [[-0.5, -0.3], [0.35, -0.3], [0.35, 0.3], [-0.5, 0.3]]
    footprint: [[0.35,0.35],[0.35,-0.35],[-0.24,-0.35],[-0.62,-0.15],[-0.62,0.15],[-0.24,0.35]]




    static_layer:
        unknown_cost_value:     0
        lethal_cost_threshold:  80
        map_topic:              "rtabmap/grid_map"
        first_map_only:         false
        subscribe_to_updates:   false
        track_unknown_space:    true
        use_maximum:            false
        trinary_costmap:        true

    obstacle_layer:
        observation_sources:         "laser_scan_front"
        max_obstacle_height:         2.0
        obstacle_range:              4.0
        raytrace_range:              3.0
        track_unknown_space:         true
        footprint_clearing_enabled:  false

        laser_scan_front:
            topic:                    "/base/laser/scan_filtered"
            sensor_frame:             "scanner_front_link"
            observation_persistence:  0.0
            expected_update_rate:     0.5
            data_type:                "LaserScan"
            clearing:                 true
            marking:                  true
            max_obstacle_height:      2.0
            min_obstacle_height:      -0.1
            obstacle_range:           4.0
            raytrace_range:           3.0
            inf_is_valid:             false


    inflation_layer:
        inflation_radius:     1.1 #0.55
        cost_scaling_factor:  10



###################################################################################################
#### LOCAL PLANNER ################################################################################

# http://wiki.ros.org/eband_local_planner#ROS_Interface
# https://github.com/utexas-bwi/eband_local_planner/blob/master/src/eband_trajectory_controller.cpp#L74

DWAPlannerROS:
    acc_lim_x: 2.5                #default : 2.5
    acc_lim_y: 0.0001              #default : 2.5
    acc_lim_theta: 3.2            #default : 3.2

    max_trans_vel: 0.9         #default : 0.55
    min_trans_vel: -0.3           #default : 0.1
    max_vel_x: 0.9              #default : 0.55
    min_vel_x: -0.3             #default : 0.0
    max_vel_y: 0.00001              #default : 0.1
    min_vel_y: -0.00001            #default : -0.1

    max_rot_vel: 0.75             #default : 1.0
    min_rot_vel: 0.2              #default : 0.4

    #acc_limit_trans: 0.3          #default : 0.1

#----------------------------------------------

    yaw_goal_tolerance: 0.1         #default : 0.05,
    xy_goal_tolerance: 0.08         #default : 0.10,
    latch_xy_goal_tolerance: true

    sim_time: 2.0                   #default : 1.7
    sim_granularity: 0.05          #default : 0.025

    #sim_period: 0.2                #default : not found
    #angular_sim_granularity: 0.1   #default : not found
    vx_samples: 10                   #default : 3
    vy_samples: 3                   #_default : 10
    vtheta_samples: 40              #_default : 20

    controller_frequency: 30.0      #_default : 20


    path_distance_bias: 50.0        #default : 32.0
    goal_distance_bias: 24.0        #default : 24.0
    occdist_scale: 0.01             #default : 0.01
    forward_point_distance: 0.425    #default : 0.325
    stop_time_buffer: 0.5           #default : 0.2
    scaling_speed: 0.25             #default : 0.25
    max_scaling_factor: 0.2         #default : 0.2

    oscillation_reset_dist: 0.05    #default : 0.05
    oscillation_reset_angle: 0.2   #default : not found

    prune_plan: true                #default: true

    trans_stopped_vel: 0.01         #default : not found
    rot_stopped_vel: 0.01           #default : not found
    #penalize_negative_x: false      #default : true
    #use_dwa: true
    #restore_defaults: false
    #publish_cost_grid_pc: true

TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_rotational_vel: 0.4
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 2.
  acc_lim_x: 1.5
  acc_lim_y: 0.

  holonomic_robot: false

  controller_frequency: 25

EBandPlannerROS:
  Ctrl_Rate: 20.0
  differential_drive: true
  max_acceleration: 0.2
  max_vel_lin: 1.3
  max_vel_th: 0.6
  min_vel_lin: 0.1
  min_vel_th: -0.6
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2


###################################################################################################
#### LOCAL COSTMAP ################################################################################

# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
# http://wiki.ros.org/costmap_2d/hydro/staticmap
# http://wiki.ros.org/costmap_2d/hydro/obstacles
# http://wiki.ros.org/costmap_2d/hydro/inflation


local_costmap:
    global_frame:              "/map"
    robot_base_frame:          "base_link"
    transform_tolerance:       0.2
    update_frequency:          5.0
    publish_frequency:         6.0
    rolling_window:            true
    always_send_full_costmap:  true
    footprint_padding:         0.01
    plugins:
     - name: obstacle_layer
       type: "costmap_2d::ObstacleLayer"
     - name: inflation_layer
       type: "costmap_2d::InflationLayer"
    #footprint: [[-0.5, -0.3], [0.35, -0.3], [0.35, 0.3], [-0.5, 0.3]]
    footprint: [[0.35,0.35],[0.35,-0.35],[-0.24,-0.35],[-0.62,-0.15],[-0.62,0.15],[-0.24,0.35]]



    width:       10.0  #
    height:      10.0  #
    resolution:  0.05 #
    origin_x:    0.0
    origin_y:    0.0

    obstacle_layer:
        observation_sources:         "laser_scan_front point_cloud"
        max_obstacle_height:         10.0
        obstacle_range:              4.0
        raytrace_range:              3.0
        track_unknown_space:         true
        footprint_clearing_enabled:  false

        laser_scan_front:
            topic:                    "/base/laser/scan_filtered"
            sensor_frame:             "scanner_front_link"
            observation_persistence:  0.0
            expected_update_rate:     0.5
            data_type:                "LaserScan"
            clearing:                 true
            marking:                  true
            max_obstacle_height:      2.0
            min_obstacle_height:      -0.1
            obstacle_range:           4.0
            raytrace_range:           3.0
            inf_is_valid:             false

        point_cloud:
            topic:                    "/velodyne_points"
            sensor_frame:             "velodyne"
            observation_persistence:  0.0
            expected_update_rate:     0.5
            data_type:                "PointCloud2"
            clearing:                 true
            marking:                  true
            max_obstacle_height:      2.0
            min_obstacle_height:      0.1
            obstacle_range:           4.0
            raytrace_range:           3.0
            inf_is_valid:             false


    inflation_layer:
        inflation_radius:     0.5
        cost_scaling_factor:  10


###################################################################################################
#### RECOVERY BEHAVIORS ###########################################################################

# http://wiki.ros.org/clear_costmap_recovery#ROS_Parameters
# http://wiki.ros.org/rotate_recovery#ROS_Parameters

recovery_behaviors:
    - name: conservative_reset
      type: clear_costmap_recovery/ClearCostmapRecovery
    - name: rotate_recovery
      type: rotate_recovery/RotateRecovery
    - name: aggressive_reset
      type: clear_costmap_recovery/ClearCostmapRecovery

conservative_reset:
    reset_distance:   1.2
    layer_names:
        - obstacle_layer

rotate_recovery:
    sim_granularity:  0.017
    frequency:        10.0

aggressive_reset:
    reset_distance:   0.36
    layer_names:
        - obstacle_layer
