obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.24,0.35],[0.24,-0.35],[-0.24,-0.35],[-0.62,-0.15],[-0.62,0.15],[-0.24,0.35]]
robot_radius: 0.25
inflation_radius: 0.40

observation_sources: laser_scanner

laser_scanner: {sensor_frame: laserfront, data_type: LaserScan, topic: sick_s300/scan_filtered, marking: true, clearing: true}
