TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_rotational_vel: 0.4
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 2.
  acc_lim_x: 1.5
  acc_lim_y: 0.

  holonomic_robot: false

  controller_frequency: 25

EBandPlannerROS:
  Ctrl_Rate: 20.0
  differential_drive: true
  max_acceleration: 0.2
  max_vel_lin: 0.6
  max_vel_th: 0.3
  min_vel_lin: 0.1
  min_vel_th: 0.0
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2



